### ISSUE TITLE
[Feature Request] Blockquote Prefix -> Support for Line Breaks `\n`

### ISSUE THREAD

**Issue by FelipeRearden** [jglev/obsidian-paste-to-current-indentation#10]
Hello @jglev !!!!!!!!

I'd like to suggest a feature that let's the user insert line breaks `\n` when creating/editing the blockquote prefix 

Here is why I'm asking you this ....

## My Workflow 

Frequently I select text using multiple cursors on Obsidian. There is a plugin called Advanced Cursors that let me create a regex query that selects multiple "items" in a note.

After selecting content with multiple cursors, I copy them to clipboard to paste somewhere else.

*When Pasting* I wanna insert a line break between the items. My idea is to use the Blockquote prefix to do this

![92A2183A-DFEA-4551-BC13-D66B15DBFC45](https://user-images.githubusercontent.com/85180696/150521493-8dbea5fa-689c-4d47-a4ce-822974f48e76.jpeg)
 
**Example**

Paste Above
```
> item 1

> item 2

> item 3
```

---

Thanks for reading this :)

Have a great day!

**Comment by jglev** [comment]
@FelipeRearden, I'm sorry to have taken this long to respond! I actually started looking into this soon after you posted it, but seem to have forgotten to write that here.

Having looked into it, I think that this is an issue that I'd prefer not to address in this plugin (vs. recommending using something like the Apply Patterns plugin's clipboard integration). It's not a problem to support newlines when pasting -- but supporting newlines when _toggling_ the blockquote marker feels like it presents a variety of edge cases that would be challenging to consistently support (i.e., not break) going forward.

Would Apply Patterns allow you to meet the need that you described above?

**Comment by FelipeRearden** [comment]
> @FelipeRearden, I'm sorry to have taken this long to respond! I actually started looking into this soon after you posted it, but seem to have forgotten to write that here.

Hello @jglev !!!! 

No problem at all 😀 I know that you busy and I have to thank you for using your time to work on your three amazing plugins !!!! 

> Having looked into it, I think that this is an issue that I'd prefer not to address in this plugin (vs. recommending using something like the Apply Patterns plugin's clipboard integration). It's not a problem to support newlines when pasting -- but supporting newlines when _toggling_ the blockquote marker feels like it presents a variety of edge cases that would be challenging to consistently support (i.e., not break) going forward.

100% understand 👍

> Would Apply Patterns allow you to meet the need that you described above? 

Yes ! That's exactly what I am using right now !

---

Thank you very much for your reply and have a great day !

P.S. I saw that we have new versions to AP and CF. I am gonna test it on Desktop and Mobile (iOS) in this next days and I let you know if I saw something :)
- Sorry that I missed these last betas.

**Comment by jglev** [comment]
Thank _you_, for all of that! :smiley:
