### ISSUE TITLE
Automatically attach code fence when pasting code

### ISSUE THREAD

**Issue by wenlzhang** [jglev/obsidian-paste-to-current-indentation#3]
One may have copied a code block in the format of text, i.e., without the code block fences being copied:
```
a + b = c
b + c = d
```

It would be great it code block fences can be automatically added around the code block when pasting the code into desired indentation with the plugin.

Maybe a new command like "Paste text as code block" can be added.

**Comment by jglev** [comment]
@wenlzhang, thank you for your suggestion!

I've addressed this just now in version `2.1.0`, which will be released imminently. I hope that that helps to address the use-case you had in mind!
