### ISSUE TITLE
Broken URL in manifest.json

### ISSUE THREAD

**Issue by claremacrae** [jglev/obsidian-paste-to-current-indentation#7]
As of the "2.0.1" release, the URL in the released manifest.json has a double `https://https://`

```json
"authorUrl": "https://https://github.com/publicus/obsidian-paste-to-current-indentation",
```

Related, it's my understanding that the authorUrl is for a link to the author rather than to the repo... but either way, it would be good for the URL to work...

**Comment by jglev** [comment]
@claremacrae, thank you!

I've updated the URL in version `2.1.0`, which will be released imminently. And I take your point about the intent of the `authorUrl` field. I may update it in the future!

**Comment by claremacrae** [comment]
Hi @jglev - thanks very much! :-)
